from repository_management_bot.src.pr_utilities import check_diff, check_pr_diff, clean_tip, count_diff, get_pr_with_user_and_branch, get_prs_with_branch, get_repo_permissions, make_pr, make_pr_branch, make_pr_commit, make_pr_fork, prep_pr_commit, push_pr_commit, flatten_pr_diff
from repository_management_bot.src.includes import *

from repository_management_bot.src.access_gh import get_user, get_user_repos, get_org_repos, get_org_repo, get_user_repo, get_repo

from repository_management_bot.src.get_template_details import RepoTemplate, AWI_TEMPLATE_REPO, AWI_ORG_NAME
from repository_management_bot.src.repo_detail import get_repo_structure, RepoStructureType

TEMPLATE = RepoTemplate()
CLONE_DIR = Path("clones")

if not CLONE_DIR.exists():
    CLONE_DIR.mkdir()

# Prepare to submit a PR
# 1. Check if the repo is missing any files
# 2. If we have permission to create a branch, create a branch
# 2.1. Else, create a fork and a branch on the fork
# 3. Create the missing files
# 4. Commit the changes to the branch
# 5. Create a PR
# 6. Done


def template_compliance_targeting(
    org_name: Optional[str] = None, 
    repo_name: Optional[str] = None, 
    user_name: Optional[str] = None,
    template_name: Optional[str] = None
    ) -> Tuple[List[Repository], RepoTemplate]:
    """template_compliance_targeting
    Take the provided arguments and interpret them to determine which repos to target
    
    Args:
        org_name (Optional[str]): the name of the organization
        repo_name (Optional[str]): the name of the repo
        user_name (Optional[str]): the name of the user
        template_name (Optional[str]): the name of the template repo
    Returns:
        target (Union[Repository, List[Repository]]): the target repo(s)
        template (RepoTemplate): the template repo
    """
    if template_name:
        if "/" in template_name:
            template = RepoTemplate(template_name)
        elif org_name:
            template = RepoTemplate(f"{org_name}/{template_name}")
        else:
            raise ValueError("Template name provided without organization")
    else:
        template = TEMPLATE
    if repo_name:
        if "/" in repo_name:
            target = get_repo(repo_name)
        elif user_name:
            target = get_user_repo(repo_name)
        elif org_name:
            target = get_org_repo(org_name, repo_name)
        else:
            raise ValueError("Repo name provided without organization or user")
        target = [target]
    elif org_name:
        target = get_org_repos(org_name)
    elif user_name:
        target = get_user_repos(user_name)
    else:
        raise ValueError("No target provided")
    return target, template

def get_compliance_diffs(
    target: Union[Repository, List[Repository]],
    template: RepoTemplate
    ) -> Dict[str, RepoStructureType]:
    """get_compliance_diffs
    Get the missing files for each repo
    
    Args:
        target (Union[Repository, List[Repository]]): the target repo(s)
        template (RepoTemplate): the template repo
        
    Returns:
        diffs (Dict[str, RepoStructureType]): the missing files for each repo (if any)
    """
    diffs = {}
    if isinstance(target, Repository):
        missing, result = check_diff(target, template)
        if missing:
            diffs[target.full_name] = result
    else:
        for repo in target:
            missing, result = check_diff(repo, template)
            if missing:
                diffs[repo.full_name] = result
    return diffs

def make_pr_body(
    repo: Repository,
    template_repo: Repository,
    changes: Dict[str, ContentFile],
    branch_name: str = "repository_management_bot/template_compliance",
) -> str:
    """make_pr_body
    Create the body for the PR.
    
    Does not do any actions on repositories, only prepares
    the body text for a PR.
    
    Args:
        repo (Repository): the target repo
        template_repo (Repository): the template repo
        changes (Dict[str, ContentFile]): the changes made
        branch_name (str): the name of the branch
    Returns:
        body (str): the body of the PR
    """
    template_repository_addr = template_repo.html_url
    organization_name = template_repo.owner.login
    organization_link = f"[{organization_name}]({template_repo.owner.html_url})"
    template_repo_link = f"[{template_repo.name}]({template_repository_addr})"
    target_repo_name = repo.full_name
    pullreq_body = f"This PR adds missing files to make the `{target_repo_name}` repository compliant with the {organization_link}'s {template_repo_link} template."
    repo_link = repo.html_url
    branch_link = f"{repo_link}/tree/{branch_name}"
    for name, content in changes.items():
        content_link = f"{branch_link}/{content.path}"
        pullreq_body += f" - Added [{name}]({content_link})\n"
    pullreq_body += "\nThis PR was automatically generated by the [Repository Management Bot]("
    pullreq_body += f"{this_repo_link})."
    return pullreq_body

def make_pr_title(*args, **kwargs) -> str:
    """make_pr_title
    Create the title for the PR.
    
    Does not do anything currently, only returns a string.
    
    Args:
        *args: positional arguments
        **kwargs: keyword arguments
    Returns:
        title (str): the title of the PR
    """
    return "Enforce Template Compliance"
    
# Splitting the previous larger function into smaller functions

def prepare_pr_changes(repo: Repository, diff: RepoStructureType, branch_name: str = "repository_management_bot/template_compliance") -> Dict[str, ContentFile]:
    """prepare_pr_changes
    Prepare the changes for a PR by adding the missing files to the tip of the repo
    
    Args:
        repo (Repository): the target repo
        template_repo (Repository): the template repo
        diff (RepoStructureType): the missing files
        branch_name (str): the name of the branch
    Returns:
        changes (Dict[str, ContentFile]): the changes that were made
    """
    branch = make_pr_branch(repo, branch_name)
    if not branch:
        return {}
    changes = make_pr_commit(repo, branch, diff)
    if len(changes) == 0:
        clean_tip(repo)
        return {}
    return changes


# given that we already have an existing PR with correct changes applied, we can attempt to update the PR
def try_update_pr_info(
    repo: Repository,
    current_pr: PullRequest,
    pr_title: str,
    pr_body: str
) -> bool:
    """try_update_pr_info
    Attempt to update the PR with new information
    
    Args:
        repo (Repository): the target repo
        current_pr (PullRequest): the current PR
        pr_title (str): the new title
        pr_body (str): the new body
    Returns:
        updated (bool): whether the PR was updated
    """
    current_pr_body = current_pr.body
    current_pr_title = current_pr.title
    if current_pr_body == pr_body and current_pr_title == pr_title:
        print(f"PR already exists with correct changes. No changes made.")
        clean_tip(repo)
        return False
    current_pr_author = current_pr.user.login
    current_user = get_user()
    if current_pr_author == current_user.login:
        current_pr.edit(title=pr_title, body=pr_body)
        print(f"Updated existing PR with up-to-date title and body.")
    elif input(f"PR already exists with correct changes, but is owned by {current_pr_author} instead of {current_user.login}. Attempt to update? (y/N): ").lower() == "y":
        try:
            current_pr.edit(title=pr_title, body=pr_body)
            print(f"Updated existing PR with up-to-date title and body.")
        except Exception as e:
            print(f"Error updating PR for {repo.full_name}: {e}")
    clean_tip(repo)
    return False

# given that a PR exists, but has incomplete or incorrect changes, we can attempt to update the PR by committing to the branch
# this only affects the relevant branch, fork, and/or commit, not the PR
def try_update_pr_branch(
    repo: Repository,
    diff: Optional[RepoStructureType] = None,
    changes: Optional[Dict[str, ContentFile]] = None,
    branch_name: str = "repository_management_bot/template_compliance",
) -> bool:
    """try_update_pr_branch
    Attempt to update the PR by committing to the branch
    
    Either `diff` or `changes` must be provided.
    
    Args:
        repo (Repository): the target repo
        diff (Optional[RepoStructureType]): the missing files
        changes (Optional[Dict[str, ContentFile]]): the changes to be made
        branch_name (str): the name of the branch
    Returns:
        updated (bool): whether the PR was updated
    """
    branch = make_pr_branch(repo, branch_name)
    if not branch:
        return False
    if not changes:
        if not diff:
            raise ValueError("Either `diff` or `changes` must be provided")
        changes = make_pr_commit(repo, branch, diff)
    if len(changes) == 0:
        clean_tip(repo)
        return False
    print(f"Local commit has {len(changes)} changes")
    query = input("Push changes to PR branch? (y/N): ")
    if query.lower() != "y":
        clean_tip(repo)
        return False
    push_pr_commit(repo, branch_name, "Add missing files to make repo compliant with template")
    clean_tip(repo)
    return True

def query_pr_continue(
    pr_body: str
) -> bool:
    """query_pr_continue
    Query the user to continue with the PR
    
    Args:
        pr_title (str): the title of the PR
        pr_body (str): the body of the PR
    Returns:
        continue (bool): whether to continue with the PR
    """
    fprint("-" * 80)
    fprint(pr_body)
    fprint("-" * 80)
    cont = input("Create PR? (y/N): ")
    return cont.lower() == "y"

# primary function will take the following arguments:
# - repo: the target repo
# - template_repo: the template repo
# - diff: the missing files
# - branch_name: the name of the branch
# #- #intend_update: #whether to attempt to update the PR if it already exists ### Not needed

# it will then logic branch into the following:
# - if the repo is already compliant, do nothing
# - calculate the changes using `flatten_pr_diff` with (diff)
#   - if no changes were made, return failure
# - calculate the PR title and body
# - then, get existing PRs
# - if a PR already exists from the current user, attempt to update the PR
#   - -> `handle_pr_update` with (repo, changes, current_pr, pr_title, pr_body)
#   - return success
# - else if no PR exists, or no PRs from the current user exist, try to create a new PR
#   - -> `handle_pr_create` with (repo, changes, branch_name, pr_title, pr_body)
#   - return success
# - else n/a
#   - return failure

# the `handle_pr_update` function will take the following arguments:
# - repo: the target repo
# - changes: the changes to be made
# - branch_name: the name of the branch
# - pr_title: the title of the PR
# - pr_body: the body of the PR

# (will only be called if a PR already exists)
# it will then logic branch into the following:
# - store a `made_changes` flag
# - if the PR has incorrect changes
#   - -> `try_update_pr_branch` with (repo, changes, branch_name)
#   - notify the user of and set `made_changes` to whether the PR branch was updated
# - if the PR has correct body and title
#   - return `made_changes`
# - if the PR has incorrect body or title
#   - -> `try_update_pr_info` with (repo, current_pr, pr_title, pr_body)
#   - notify the user of and set `made_changes = made_changes or success`
# - return `made_changes`

# the `handle_pr_create` function will take the following arguments:
# - repo: the target repo
# - changes: the changes to be made
# - branch_name: the name of the branch
# - pr_title: the title of the PR
# - pr_body: the body of the PR

# (will only be called if no PR exists, or confirmed when a PR exists but is not owned by the current user)
# unlike update, this function will not require intensive branching
# - branch = make_pr_branch(repo, branch_name)
# - if branch is None, return failure
# - changes = make_pr_commit(repo, branch, changes)
# - if no changes were made:
#  - clean_tip(repo)
#  - return failure
# - if not query_pr_continue(pr_body):
#  - clean_tip(repo)
#  - return failure
# - push_pr_commit(repo, branch_name, "Add missing files to make repo compliant with template")
# - make_pr(repo, repo, branch, pr_title, pr_body)
# - clean_tip(repo)
# - return success

def handle_pr_update(
    repo: Repository,
    repotemplate: RepoTemplate,
    changes: Dict[str, ContentFile],
    current_pr: PullRequest,
    pr_title: str,
    pr_body: str
) -> bool:
    """handle_pr_update
    Handle updating an existing PR
    
    Args:
        repo (Repository): the target repo
        changes (Dict[str, ContentFile]): the changes to be made
        current_pr (PullRequest): the current PR
        pr_title (str): the title of the PR
        pr_body (str): the body of the PR
    Returns:
        updated (bool): whether the PR was updated
    """
    made_changes = False
    if current_pr:
        fprint(f"PR already exists for {repo.full_name} with branch {current_pr.head.ref}.")
        has_diffs, same_pr_diff = check_pr_diff(current_pr, repotemplate)
        if has_diffs:
            made_changes = try_update_pr_branch(repo, changes=changes) or made_changes
        made_changes = try_update_pr_info(repo, current_pr, pr_title, pr_body) or made_changes
    return made_changes

def handle_pr_create(
    repo: Repository,
    diff: RepoStructureType,
    branch_name: str,
    pr_title: str,
    pr_body: str
) -> bool:
    """handle_pr_create
    Handle creating a new PR
    
    Args:
        repo (Repository): the target repo
        diff (RepoStructureType): the missing files
        branch_name (str): the name of the branch
        pr_title (str): the title of the PR
        pr_body (str): the body of the PR
    Returns:
        created (bool): whether the PR was created
    """
    branch = make_pr_branch(repo, branch_name)
    if not branch:
        return False
    changes = make_pr_commit(repo, branch, diff)
    if len(changes) == 0:
        clean_tip(repo)
        return False
    if not query_pr_continue(pr_body):
        clean_tip(repo)
        return False
    push_pr_commit(repo, branch_name, "Add missing files to make repo compliant with template")
    make_pr(repo, repo, branch, pr_title, pr_body)
    clean_tip(repo)
    return True

def handle_compliance_pr(
    repo: Repository,
    repotemplate: RepoTemplate,
    diff: Optional[RepoStructureType] = None,
    branch_name: str = "repository_management_bot/template_compliance",
) -> bool:
    """handle_compliance_pr
    Create or update a PR to make the repo compliant with the template
    
    Replacing the previous `make_compliance_pr` and `handle_pr_dispatch` functions
    
    Args:
        repo (Repository): the target repo
        template_repo (RepoTemplate): the template repo
        diff (Optional[RepoStructureType]): the missing files
        branch_name (str): the name of the branch
    Returns:
        success (bool): whether the PR was created or updated
    """
    current_user = get_user().login
    if not diff:
        diff = get_compliance_diffs(repo, repotemplate)[repo.full_name]
    changes = flatten_pr_diff(diff)
    if len(changes) == 0:
        fprint(f"{repo.full_name} is already compliant. Skipping further checks.")
        return False
    else:
        fprint(f"{repo.full_name} is missing at least {len(changes)} files")
    
    pr_title = make_pr_title(repo, repotemplate, changes, branch_name)
    pr_body = make_pr_body(repo, repotemplate.template_repo, changes, branch_name)
    
    current_pr = get_pr_with_user_and_branch(repo, current_user, branch_name)
    current_prs = get_prs_with_branch(repo, branch_name)
    if current_pr:
        return handle_pr_update(repo, repotemplate, changes, current_pr, pr_title, pr_body)
    elif current_prs:
        plural = len(current_prs) > 1
        msg = f"{len(current_prs)} PR" + ("s" if plural else "") + " already exist" + ("" if plural else "s") + f" for {repo.full_name} with branch {branch_name}."
        fprint(msg)
        fprint(f"PR author" + ("s" if plural else "") + f": {', '.join(pr.user.login for pr in current_prs)}")
        # if input(f"Attempt to create new PR for {repo.full_name}? (y/N): ").lower() != "y":
        #     return False
        fprint(f"Github API does not allow for creating multiple PRs for the same branch. Skipping.")
        return False
    return handle_pr_create(repo, diff, branch_name, pr_title, pr_body)

def compliance_pr_dispatch(
    user_name: Optional[str] = None,
    org_name: Optional[str] = None,
    repo_name: Optional[str] = None,
    template_name: Optional[str] = None
):
    """compliance_pr_dispatch
    Create PRs to make the target repo(s) compliant with the template
    
    Args:
        user_name (Optional[str]): the name of the user
        org_name (Optional[str]): the name of the organization
        repo_name (Optional[str]): the name of the repo
        template_name (Optional[str]): the name of the template repo
    """
    target, template = template_compliance_targeting(
        user_name=user_name,
        org_name=org_name,
        repo_name=repo_name,
        template_name=template_name
    )
    branch_name = "repository_management_bot/template_compliance"
    fprint(f"Targeting {target} with template {template.template_repo.full_name}")
    result = []
    if len(target) == 1:
        repo = target[0]
        res = handle_compliance_pr(
            repo,
            template,
            branch_name=branch_name
        )
        if res:
            result.append(repo.full_name)
    else:
        diffs = get_compliance_diffs(target, template)
        for repo in target:
            diff = diffs[repo.full_name]
            res = handle_compliance_pr(
                repo,
                template,
                diff=diff,
                branch_name=branch_name
            )
            if res:
                result.append(repo.full_name)
    fprint(f"PRs created for {len(result)} repos")
    if result:
        fprint(result)
    return
    
    

if __name__ == "__main__":
    def test_permissions():
        # Get the 'bmi_rainrate' repo
        repo = get_org_repo(AWI_ORG_NAME, "bmi_rainrate")
        perms = get_repo_permissions(repo)
        fprint(perms)
    # test_permissions()
    
    def test_pr_commit_prep():
        repo = get_user_repo("load_factorio_data")
        missing, structure = check_diff(repo)
        fprint(missing, structure)
        if not structure:
            return
        branch = make_pr_branch(repo, "test-branch")
        fprint(branch)
        fprint(missing, structure)
        if not branch:
            return
        make_pr_commit(repo, branch, structure)
        # remove branch
        os.system(f"cd {CLONE_DIR / repo.full_name} && git branch -D test-branch")
        clean_tip(repo)
        